service: ravendb
display_name: Ravendb
entities:
- name: node
  metrics:
  - provider_name: ravendb_document_put_bytes
    description: Server-wide document put bytes
    type: counter
  - provider_name: ravendb_document_put
    description: Server-wide document puts count
    type: counter
  - provider_name: ravendb_cpu_time_seconds
    description: CPU time
    type: counter
  - provider_name: ravendb_is_leader
    description: If 1, then node is the cluster leader, otherwise 0
    type: gauge
  - provider_name: ravendb_mapindex_indexed
    description: Server-wide map index indexed count
    type: counter
  - provider_name: ravendb_mapreduceindex_mapped
    description: Server-wide map-reduce index mapped count
    type: counter
  - provider_name: ravendb_mapreduceindex_reduced
    description: Server-wide map-reduce index reduced count
    type: counter
  - provider_name: ravendb_request
    description: Server-wide request count
    type: counter
  - provider_name: ravendb_up
    description: Whether the RavenDB scrape was successful
    type: gauge
  - provider_name: ravendb_working_set_bytes
    description: Process working set
    type: gauge
- name: database
  properties:
    dimensions: [database]
  metrics:
  - provider_name: ravendb_database_document_put_bytes
    description: Database document put bytes
    type: counter
    labels:
    - database
  - provider_name: ravendb_database_document_put
    description: Database document puts count
    type: counter
    labels:
    - database
  - provider_name: ravendb_database_documents
    description: Count of documents in a database
    type: gauge
    labels:
    - database
  - provider_name: ravendb_database_indexes
    description: Count of indexes in a database
    type: gauge
    labels:
    - database
  - provider_name: ravendb_database_mapindex_indexed
    description: Database map index indexed count
    type: counter
    labels:
    - database
  - provider_name: ravendb_database_mapreduceindex_mapped
    description: Database map-reduce index mapped count
    type: counter
    labels:
    - database
  - provider_name: ravendb_database_mapreduceindex_reduced
    description: Database map-reduce index reduced count
    type: counter
    labels:
    - database
  - provider_name: ravendb_database_request
    description: Database request count
    type: counter
    labels:
    - database
  - provider_name: ravendb_database_size_bytes
    description: Database size in bytes
    type: gauge
    labels:
    - database
  - provider_name: ravendb_database_stale_indexes
    description: Count of stale indexes in a database
    type: gauge
    labels:
    - database
