name: validate definition file
on:
  pull_request:
jobs:
  validate:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm --prefix validator install
      - name: Validate
        run: npm --prefix validator run check
